/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as mainDashboardRouteRouteImport } from './routes/(main)/dashboard/route'
import { Route as mainPagesIndexRouteImport } from './routes/(main)/pages/index'
import { Route as mainDashboardIndexRouteImport } from './routes/(main)/dashboard/index'
import { Route as mainDashboardSubscribeRouteImport } from './routes/(main)/dashboard/subscribe'
import { Route as mainDashboardPaymentRouteImport } from './routes/(main)/dashboard/payment'
import { Route as mainAuthenticationMagicRouteImport } from './routes/(main)/authentication/magic'
import { Route as mainPagesLayoutRouteRouteImport } from './routes/(main)/pages/_layout/route'
import { Route as mainDashboardOnboardingsIndexRouteImport } from './routes/(main)/dashboard/onboardings/index'
import { Route as mainPagesLayoutSlugRouteImport } from './routes/(main)/pages/_layout/$slug'
import { Route as mainDashboardOnboardingsProfileRouteImport } from './routes/(main)/dashboard/onboardings/profile'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainDashboardRouteRoute = mainDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainPagesIndexRoute = mainPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainDashboardIndexRoute = mainDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardSubscribeRoute = mainDashboardSubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardPaymentRoute = mainDashboardPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainAuthenticationMagicRoute = mainAuthenticationMagicRouteImport.update({
  id: '/authentication/magic',
  path: '/authentication/magic',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainPagesLayoutRouteRoute = mainPagesLayoutRouteRouteImport.update({
  id: '/pages/_layout',
  path: '/pages',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainDashboardOnboardingsIndexRoute =
  mainDashboardOnboardingsIndexRouteImport.update({
    id: '/onboardings/',
    path: '/onboardings/',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainPagesLayoutSlugRoute = mainPagesLayoutSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => mainPagesLayoutRouteRoute,
} as any)
const mainDashboardOnboardingsProfileRoute =
  mainDashboardOnboardingsProfileRouteImport.update({
    id: '/onboardings/profile',
    path: '/onboardings/profile',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof mainDashboardRouteRouteWithChildren
  '/pages': typeof mainPagesLayoutRouteRouteWithChildren
  '/authentication/magic': typeof mainAuthenticationMagicRoute
  '/dashboard/payment': typeof mainDashboardPaymentRoute
  '/dashboard/subscribe': typeof mainDashboardSubscribeRoute
  '/dashboard/': typeof mainDashboardIndexRoute
  '/pages/': typeof mainPagesIndexRoute
  '/dashboard/onboardings/profile': typeof mainDashboardOnboardingsProfileRoute
  '/pages/$slug': typeof mainPagesLayoutSlugRoute
  '/dashboard/onboardings/': typeof mainDashboardOnboardingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pages': typeof mainPagesIndexRoute
  '/authentication/magic': typeof mainAuthenticationMagicRoute
  '/dashboard/payment': typeof mainDashboardPaymentRoute
  '/dashboard/subscribe': typeof mainDashboardSubscribeRoute
  '/dashboard': typeof mainDashboardIndexRoute
  '/dashboard/onboardings/profile': typeof mainDashboardOnboardingsProfileRoute
  '/pages/$slug': typeof mainPagesLayoutSlugRoute
  '/dashboard/onboardings': typeof mainDashboardOnboardingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(main)': typeof mainRouteRouteWithChildren
  '/(main)/dashboard': typeof mainDashboardRouteRouteWithChildren
  '/(main)/pages/_layout': typeof mainPagesLayoutRouteRouteWithChildren
  '/(main)/authentication/magic': typeof mainAuthenticationMagicRoute
  '/(main)/dashboard/payment': typeof mainDashboardPaymentRoute
  '/(main)/dashboard/subscribe': typeof mainDashboardSubscribeRoute
  '/(main)/dashboard/': typeof mainDashboardIndexRoute
  '/(main)/pages/': typeof mainPagesIndexRoute
  '/(main)/dashboard/onboardings/profile': typeof mainDashboardOnboardingsProfileRoute
  '/(main)/pages/_layout/$slug': typeof mainPagesLayoutSlugRoute
  '/(main)/dashboard/onboardings/': typeof mainDashboardOnboardingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/pages'
    | '/authentication/magic'
    | '/dashboard/payment'
    | '/dashboard/subscribe'
    | '/dashboard/'
    | '/pages/'
    | '/dashboard/onboardings/profile'
    | '/pages/$slug'
    | '/dashboard/onboardings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pages'
    | '/authentication/magic'
    | '/dashboard/payment'
    | '/dashboard/subscribe'
    | '/dashboard'
    | '/dashboard/onboardings/profile'
    | '/pages/$slug'
    | '/dashboard/onboardings'
  id:
    | '__root__'
    | '/'
    | '/(main)'
    | '/(main)/dashboard'
    | '/(main)/pages/_layout'
    | '/(main)/authentication/magic'
    | '/(main)/dashboard/payment'
    | '/(main)/dashboard/subscribe'
    | '/(main)/dashboard/'
    | '/(main)/pages/'
    | '/(main)/dashboard/onboardings/profile'
    | '/(main)/pages/_layout/$slug'
    | '/(main)/dashboard/onboardings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  mainRouteRoute: typeof mainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/dashboard': {
      id: '/(main)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof mainDashboardRouteRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/pages/': {
      id: '/(main)/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof mainPagesIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/dashboard/': {
      id: '/(main)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof mainDashboardIndexRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/subscribe': {
      id: '/(main)/dashboard/subscribe'
      path: '/subscribe'
      fullPath: '/dashboard/subscribe'
      preLoaderRoute: typeof mainDashboardSubscribeRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/payment': {
      id: '/(main)/dashboard/payment'
      path: '/payment'
      fullPath: '/dashboard/payment'
      preLoaderRoute: typeof mainDashboardPaymentRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/authentication/magic': {
      id: '/(main)/authentication/magic'
      path: '/authentication/magic'
      fullPath: '/authentication/magic'
      preLoaderRoute: typeof mainAuthenticationMagicRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/pages/_layout': {
      id: '/(main)/pages/_layout'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof mainPagesLayoutRouteRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/dashboard/onboardings/': {
      id: '/(main)/dashboard/onboardings/'
      path: '/onboardings'
      fullPath: '/dashboard/onboardings/'
      preLoaderRoute: typeof mainDashboardOnboardingsIndexRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/pages/_layout/$slug': {
      id: '/(main)/pages/_layout/$slug'
      path: '/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof mainPagesLayoutSlugRouteImport
      parentRoute: typeof mainPagesLayoutRouteRoute
    }
    '/(main)/dashboard/onboardings/profile': {
      id: '/(main)/dashboard/onboardings/profile'
      path: '/onboardings/profile'
      fullPath: '/dashboard/onboardings/profile'
      preLoaderRoute: typeof mainDashboardOnboardingsProfileRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
  }
}

interface mainDashboardRouteRouteChildren {
  mainDashboardPaymentRoute: typeof mainDashboardPaymentRoute
  mainDashboardSubscribeRoute: typeof mainDashboardSubscribeRoute
  mainDashboardIndexRoute: typeof mainDashboardIndexRoute
  mainDashboardOnboardingsProfileRoute: typeof mainDashboardOnboardingsProfileRoute
  mainDashboardOnboardingsIndexRoute: typeof mainDashboardOnboardingsIndexRoute
}

const mainDashboardRouteRouteChildren: mainDashboardRouteRouteChildren = {
  mainDashboardPaymentRoute: mainDashboardPaymentRoute,
  mainDashboardSubscribeRoute: mainDashboardSubscribeRoute,
  mainDashboardIndexRoute: mainDashboardIndexRoute,
  mainDashboardOnboardingsProfileRoute: mainDashboardOnboardingsProfileRoute,
  mainDashboardOnboardingsIndexRoute: mainDashboardOnboardingsIndexRoute,
}

const mainDashboardRouteRouteWithChildren =
  mainDashboardRouteRoute._addFileChildren(mainDashboardRouteRouteChildren)

interface mainPagesLayoutRouteRouteChildren {
  mainPagesLayoutSlugRoute: typeof mainPagesLayoutSlugRoute
}

const mainPagesLayoutRouteRouteChildren: mainPagesLayoutRouteRouteChildren = {
  mainPagesLayoutSlugRoute: mainPagesLayoutSlugRoute,
}

const mainPagesLayoutRouteRouteWithChildren =
  mainPagesLayoutRouteRoute._addFileChildren(mainPagesLayoutRouteRouteChildren)

interface mainRouteRouteChildren {
  mainDashboardRouteRoute: typeof mainDashboardRouteRouteWithChildren
  mainPagesLayoutRouteRoute: typeof mainPagesLayoutRouteRouteWithChildren
  mainAuthenticationMagicRoute: typeof mainAuthenticationMagicRoute
  mainPagesIndexRoute: typeof mainPagesIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainDashboardRouteRoute: mainDashboardRouteRouteWithChildren,
  mainPagesLayoutRouteRoute: mainPagesLayoutRouteRouteWithChildren,
  mainAuthenticationMagicRoute: mainAuthenticationMagicRoute,
  mainPagesIndexRoute: mainPagesIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  mainRouteRoute: mainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
