/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as mainPagesIndexRouteImport } from './routes/(main)/pages/index'
import { Route as mainDashboardIndexRouteImport } from './routes/(main)/dashboard/index'
import { Route as mainDashboardWhatsappRouteImport } from './routes/(main)/dashboard/whatsapp'
import { Route as mainDashboardSubscribeRouteImport } from './routes/(main)/dashboard/subscribe'
import { Route as mainDashboardPaymentRouteImport } from './routes/(main)/dashboard/payment'
import { Route as mainAuthenticationMagicRouteImport } from './routes/(main)/authentication/magic'
import { Route as mainPagesLayoutRouteRouteImport } from './routes/(main)/pages/_layout/route'
import { Route as mainDashboardOnboardingsIndexRouteImport } from './routes/(main)/dashboard/onboardings/index'
import { Route as mainPagesLayoutTermsOfServiceRouteImport } from './routes/(main)/pages/_layout/terms-of-service'
import { Route as mainPagesLayoutPrivacyPolicyRouteImport } from './routes/(main)/pages/_layout/privacy-policy'
import { Route as mainPagesLayoutHelpRouteImport } from './routes/(main)/pages/_layout/help'
import { Route as mainPagesLayoutContactRouteImport } from './routes/(main)/pages/_layout/contact'
import { Route as mainPagesLayoutAboutRouteImport } from './routes/(main)/pages/_layout/about'
import { Route as mainDashboardOnboardingsProfileRouteImport } from './routes/(main)/dashboard/onboardings/profile'
import { Route as mainDashboardOnboardingsAgentRouteImport } from './routes/(main)/dashboard/onboardings/agent'

const mainPagesRouteImport = createFileRoute('/(main)/pages')()

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainPagesRoute = mainPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainPagesIndexRoute = mainPagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainPagesRoute,
} as any)
const mainDashboardIndexRoute = mainDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainDashboardWhatsappRoute = mainDashboardWhatsappRouteImport.update({
  id: '/dashboard/whatsapp',
  path: '/dashboard/whatsapp',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainDashboardSubscribeRoute = mainDashboardSubscribeRouteImport.update({
  id: '/dashboard/subscribe',
  path: '/dashboard/subscribe',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainDashboardPaymentRoute = mainDashboardPaymentRouteImport.update({
  id: '/dashboard/payment',
  path: '/dashboard/payment',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAuthenticationMagicRoute = mainAuthenticationMagicRouteImport.update({
  id: '/authentication/magic',
  path: '/authentication/magic',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainPagesLayoutRouteRoute = mainPagesLayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => mainPagesRoute,
} as any)
const mainDashboardOnboardingsIndexRoute =
  mainDashboardOnboardingsIndexRouteImport.update({
    id: '/dashboard/onboardings/',
    path: '/dashboard/onboardings/',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainPagesLayoutTermsOfServiceRoute =
  mainPagesLayoutTermsOfServiceRouteImport.update({
    id: '/terms-of-service',
    path: '/terms-of-service',
    getParentRoute: () => mainPagesLayoutRouteRoute,
  } as any)
const mainPagesLayoutPrivacyPolicyRoute =
  mainPagesLayoutPrivacyPolicyRouteImport.update({
    id: '/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => mainPagesLayoutRouteRoute,
  } as any)
const mainPagesLayoutHelpRoute = mainPagesLayoutHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => mainPagesLayoutRouteRoute,
} as any)
const mainPagesLayoutContactRoute = mainPagesLayoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => mainPagesLayoutRouteRoute,
} as any)
const mainPagesLayoutAboutRoute = mainPagesLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => mainPagesLayoutRouteRoute,
} as any)
const mainDashboardOnboardingsProfileRoute =
  mainDashboardOnboardingsProfileRouteImport.update({
    id: '/dashboard/onboardings/profile',
    path: '/dashboard/onboardings/profile',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainDashboardOnboardingsAgentRoute =
  mainDashboardOnboardingsAgentRouteImport.update({
    id: '/dashboard/onboardings/agent',
    path: '/dashboard/onboardings/agent',
    getParentRoute: () => mainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pages': typeof mainPagesLayoutRouteRouteWithChildren
  '/authentication/magic': typeof mainAuthenticationMagicRoute
  '/dashboard/payment': typeof mainDashboardPaymentRoute
  '/dashboard/subscribe': typeof mainDashboardSubscribeRoute
  '/dashboard/whatsapp': typeof mainDashboardWhatsappRoute
  '/dashboard': typeof mainDashboardIndexRoute
  '/pages/': typeof mainPagesIndexRoute
  '/dashboard/onboardings/agent': typeof mainDashboardOnboardingsAgentRoute
  '/dashboard/onboardings/profile': typeof mainDashboardOnboardingsProfileRoute
  '/pages/about': typeof mainPagesLayoutAboutRoute
  '/pages/contact': typeof mainPagesLayoutContactRoute
  '/pages/help': typeof mainPagesLayoutHelpRoute
  '/pages/privacy-policy': typeof mainPagesLayoutPrivacyPolicyRoute
  '/pages/terms-of-service': typeof mainPagesLayoutTermsOfServiceRoute
  '/dashboard/onboardings': typeof mainDashboardOnboardingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pages': typeof mainPagesIndexRoute
  '/authentication/magic': typeof mainAuthenticationMagicRoute
  '/dashboard/payment': typeof mainDashboardPaymentRoute
  '/dashboard/subscribe': typeof mainDashboardSubscribeRoute
  '/dashboard/whatsapp': typeof mainDashboardWhatsappRoute
  '/dashboard': typeof mainDashboardIndexRoute
  '/dashboard/onboardings/agent': typeof mainDashboardOnboardingsAgentRoute
  '/dashboard/onboardings/profile': typeof mainDashboardOnboardingsProfileRoute
  '/pages/about': typeof mainPagesLayoutAboutRoute
  '/pages/contact': typeof mainPagesLayoutContactRoute
  '/pages/help': typeof mainPagesLayoutHelpRoute
  '/pages/privacy-policy': typeof mainPagesLayoutPrivacyPolicyRoute
  '/pages/terms-of-service': typeof mainPagesLayoutTermsOfServiceRoute
  '/dashboard/onboardings': typeof mainDashboardOnboardingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(main)': typeof mainRouteRouteWithChildren
  '/(main)/pages': typeof mainPagesRouteWithChildren
  '/(main)/pages/_layout': typeof mainPagesLayoutRouteRouteWithChildren
  '/(main)/authentication/magic': typeof mainAuthenticationMagicRoute
  '/(main)/dashboard/payment': typeof mainDashboardPaymentRoute
  '/(main)/dashboard/subscribe': typeof mainDashboardSubscribeRoute
  '/(main)/dashboard/whatsapp': typeof mainDashboardWhatsappRoute
  '/(main)/dashboard/': typeof mainDashboardIndexRoute
  '/(main)/pages/': typeof mainPagesIndexRoute
  '/(main)/dashboard/onboardings/agent': typeof mainDashboardOnboardingsAgentRoute
  '/(main)/dashboard/onboardings/profile': typeof mainDashboardOnboardingsProfileRoute
  '/(main)/pages/_layout/about': typeof mainPagesLayoutAboutRoute
  '/(main)/pages/_layout/contact': typeof mainPagesLayoutContactRoute
  '/(main)/pages/_layout/help': typeof mainPagesLayoutHelpRoute
  '/(main)/pages/_layout/privacy-policy': typeof mainPagesLayoutPrivacyPolicyRoute
  '/(main)/pages/_layout/terms-of-service': typeof mainPagesLayoutTermsOfServiceRoute
  '/(main)/dashboard/onboardings/': typeof mainDashboardOnboardingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pages'
    | '/authentication/magic'
    | '/dashboard/payment'
    | '/dashboard/subscribe'
    | '/dashboard/whatsapp'
    | '/dashboard'
    | '/pages/'
    | '/dashboard/onboardings/agent'
    | '/dashboard/onboardings/profile'
    | '/pages/about'
    | '/pages/contact'
    | '/pages/help'
    | '/pages/privacy-policy'
    | '/pages/terms-of-service'
    | '/dashboard/onboardings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pages'
    | '/authentication/magic'
    | '/dashboard/payment'
    | '/dashboard/subscribe'
    | '/dashboard/whatsapp'
    | '/dashboard'
    | '/dashboard/onboardings/agent'
    | '/dashboard/onboardings/profile'
    | '/pages/about'
    | '/pages/contact'
    | '/pages/help'
    | '/pages/privacy-policy'
    | '/pages/terms-of-service'
    | '/dashboard/onboardings'
  id:
    | '__root__'
    | '/'
    | '/(main)'
    | '/(main)/pages'
    | '/(main)/pages/_layout'
    | '/(main)/authentication/magic'
    | '/(main)/dashboard/payment'
    | '/(main)/dashboard/subscribe'
    | '/(main)/dashboard/whatsapp'
    | '/(main)/dashboard/'
    | '/(main)/pages/'
    | '/(main)/dashboard/onboardings/agent'
    | '/(main)/dashboard/onboardings/profile'
    | '/(main)/pages/_layout/about'
    | '/(main)/pages/_layout/contact'
    | '/(main)/pages/_layout/help'
    | '/(main)/pages/_layout/privacy-policy'
    | '/(main)/pages/_layout/terms-of-service'
    | '/(main)/dashboard/onboardings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  mainRouteRoute: typeof mainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/pages': {
      id: '/(main)/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof mainPagesRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/pages/': {
      id: '/(main)/pages/'
      path: '/'
      fullPath: '/pages/'
      preLoaderRoute: typeof mainPagesIndexRouteImport
      parentRoute: typeof mainPagesRoute
    }
    '/(main)/dashboard/': {
      id: '/(main)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof mainDashboardIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/dashboard/whatsapp': {
      id: '/(main)/dashboard/whatsapp'
      path: '/dashboard/whatsapp'
      fullPath: '/dashboard/whatsapp'
      preLoaderRoute: typeof mainDashboardWhatsappRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/dashboard/subscribe': {
      id: '/(main)/dashboard/subscribe'
      path: '/dashboard/subscribe'
      fullPath: '/dashboard/subscribe'
      preLoaderRoute: typeof mainDashboardSubscribeRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/dashboard/payment': {
      id: '/(main)/dashboard/payment'
      path: '/dashboard/payment'
      fullPath: '/dashboard/payment'
      preLoaderRoute: typeof mainDashboardPaymentRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/authentication/magic': {
      id: '/(main)/authentication/magic'
      path: '/authentication/magic'
      fullPath: '/authentication/magic'
      preLoaderRoute: typeof mainAuthenticationMagicRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/pages/_layout': {
      id: '/(main)/pages/_layout'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof mainPagesLayoutRouteRouteImport
      parentRoute: typeof mainPagesRoute
    }
    '/(main)/dashboard/onboardings/': {
      id: '/(main)/dashboard/onboardings/'
      path: '/dashboard/onboardings'
      fullPath: '/dashboard/onboardings'
      preLoaderRoute: typeof mainDashboardOnboardingsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/pages/_layout/terms-of-service': {
      id: '/(main)/pages/_layout/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/pages/terms-of-service'
      preLoaderRoute: typeof mainPagesLayoutTermsOfServiceRouteImport
      parentRoute: typeof mainPagesLayoutRouteRoute
    }
    '/(main)/pages/_layout/privacy-policy': {
      id: '/(main)/pages/_layout/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/pages/privacy-policy'
      preLoaderRoute: typeof mainPagesLayoutPrivacyPolicyRouteImport
      parentRoute: typeof mainPagesLayoutRouteRoute
    }
    '/(main)/pages/_layout/help': {
      id: '/(main)/pages/_layout/help'
      path: '/help'
      fullPath: '/pages/help'
      preLoaderRoute: typeof mainPagesLayoutHelpRouteImport
      parentRoute: typeof mainPagesLayoutRouteRoute
    }
    '/(main)/pages/_layout/contact': {
      id: '/(main)/pages/_layout/contact'
      path: '/contact'
      fullPath: '/pages/contact'
      preLoaderRoute: typeof mainPagesLayoutContactRouteImport
      parentRoute: typeof mainPagesLayoutRouteRoute
    }
    '/(main)/pages/_layout/about': {
      id: '/(main)/pages/_layout/about'
      path: '/about'
      fullPath: '/pages/about'
      preLoaderRoute: typeof mainPagesLayoutAboutRouteImport
      parentRoute: typeof mainPagesLayoutRouteRoute
    }
    '/(main)/dashboard/onboardings/profile': {
      id: '/(main)/dashboard/onboardings/profile'
      path: '/dashboard/onboardings/profile'
      fullPath: '/dashboard/onboardings/profile'
      preLoaderRoute: typeof mainDashboardOnboardingsProfileRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/dashboard/onboardings/agent': {
      id: '/(main)/dashboard/onboardings/agent'
      path: '/dashboard/onboardings/agent'
      fullPath: '/dashboard/onboardings/agent'
      preLoaderRoute: typeof mainDashboardOnboardingsAgentRouteImport
      parentRoute: typeof mainRouteRoute
    }
  }
}

interface mainPagesLayoutRouteRouteChildren {
  mainPagesLayoutAboutRoute: typeof mainPagesLayoutAboutRoute
  mainPagesLayoutContactRoute: typeof mainPagesLayoutContactRoute
  mainPagesLayoutHelpRoute: typeof mainPagesLayoutHelpRoute
  mainPagesLayoutPrivacyPolicyRoute: typeof mainPagesLayoutPrivacyPolicyRoute
  mainPagesLayoutTermsOfServiceRoute: typeof mainPagesLayoutTermsOfServiceRoute
}

const mainPagesLayoutRouteRouteChildren: mainPagesLayoutRouteRouteChildren = {
  mainPagesLayoutAboutRoute: mainPagesLayoutAboutRoute,
  mainPagesLayoutContactRoute: mainPagesLayoutContactRoute,
  mainPagesLayoutHelpRoute: mainPagesLayoutHelpRoute,
  mainPagesLayoutPrivacyPolicyRoute: mainPagesLayoutPrivacyPolicyRoute,
  mainPagesLayoutTermsOfServiceRoute: mainPagesLayoutTermsOfServiceRoute,
}

const mainPagesLayoutRouteRouteWithChildren =
  mainPagesLayoutRouteRoute._addFileChildren(mainPagesLayoutRouteRouteChildren)

interface mainPagesRouteChildren {
  mainPagesLayoutRouteRoute: typeof mainPagesLayoutRouteRouteWithChildren
  mainPagesIndexRoute: typeof mainPagesIndexRoute
}

const mainPagesRouteChildren: mainPagesRouteChildren = {
  mainPagesLayoutRouteRoute: mainPagesLayoutRouteRouteWithChildren,
  mainPagesIndexRoute: mainPagesIndexRoute,
}

const mainPagesRouteWithChildren = mainPagesRoute._addFileChildren(
  mainPagesRouteChildren,
)

interface mainRouteRouteChildren {
  mainPagesRoute: typeof mainPagesRouteWithChildren
  mainAuthenticationMagicRoute: typeof mainAuthenticationMagicRoute
  mainDashboardPaymentRoute: typeof mainDashboardPaymentRoute
  mainDashboardSubscribeRoute: typeof mainDashboardSubscribeRoute
  mainDashboardWhatsappRoute: typeof mainDashboardWhatsappRoute
  mainDashboardIndexRoute: typeof mainDashboardIndexRoute
  mainDashboardOnboardingsAgentRoute: typeof mainDashboardOnboardingsAgentRoute
  mainDashboardOnboardingsProfileRoute: typeof mainDashboardOnboardingsProfileRoute
  mainDashboardOnboardingsIndexRoute: typeof mainDashboardOnboardingsIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainPagesRoute: mainPagesRouteWithChildren,
  mainAuthenticationMagicRoute: mainAuthenticationMagicRoute,
  mainDashboardPaymentRoute: mainDashboardPaymentRoute,
  mainDashboardSubscribeRoute: mainDashboardSubscribeRoute,
  mainDashboardWhatsappRoute: mainDashboardWhatsappRoute,
  mainDashboardIndexRoute: mainDashboardIndexRoute,
  mainDashboardOnboardingsAgentRoute: mainDashboardOnboardingsAgentRoute,
  mainDashboardOnboardingsProfileRoute: mainDashboardOnboardingsProfileRoute,
  mainDashboardOnboardingsIndexRoute: mainDashboardOnboardingsIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  mainRouteRoute: mainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
