/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as mainPagesIndexRouteImport } from './routes/(main)/pages/index'
import { Route as mainDashboardIndexRouteImport } from './routes/(main)/dashboard/index'
import { Route as mainPagesTermsOfServiceRouteImport } from './routes/(main)/pages/terms-of-service'
import { Route as mainPagesPrivacyPolicyRouteImport } from './routes/(main)/pages/privacy-policy'
import { Route as mainPagesHelpRouteImport } from './routes/(main)/pages/help'
import { Route as mainPagesContactRouteImport } from './routes/(main)/pages/contact'
import { Route as mainPagesAboutRouteImport } from './routes/(main)/pages/about'
import { Route as mainDashboardWhatsappRouteImport } from './routes/(main)/dashboard/whatsapp'
import { Route as mainDashboardSubscribeRouteImport } from './routes/(main)/dashboard/subscribe'
import { Route as mainDashboardPaymentRouteImport } from './routes/(main)/dashboard/payment'
import { Route as mainAuthenticationMagicRouteImport } from './routes/(main)/authentication/magic'
import { Route as mainDashboardOnboardingsIndexRouteImport } from './routes/(main)/dashboard/onboardings/index'
import { Route as mainDashboardOnboardingsProfileRouteImport } from './routes/(main)/dashboard/onboardings/profile'
import { Route as mainDashboardOnboardingsAgentRouteImport } from './routes/(main)/dashboard/onboardings/agent'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainPagesIndexRoute = mainPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainDashboardIndexRoute = mainDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainPagesTermsOfServiceRoute = mainPagesTermsOfServiceRouteImport.update({
  id: '/pages/terms-of-service',
  path: '/pages/terms-of-service',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainPagesPrivacyPolicyRoute = mainPagesPrivacyPolicyRouteImport.update({
  id: '/pages/privacy-policy',
  path: '/pages/privacy-policy',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainPagesHelpRoute = mainPagesHelpRouteImport.update({
  id: '/pages/help',
  path: '/pages/help',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainPagesContactRoute = mainPagesContactRouteImport.update({
  id: '/pages/contact',
  path: '/pages/contact',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainPagesAboutRoute = mainPagesAboutRouteImport.update({
  id: '/pages/about',
  path: '/pages/about',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainDashboardWhatsappRoute = mainDashboardWhatsappRouteImport.update({
  id: '/dashboard/whatsapp',
  path: '/dashboard/whatsapp',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainDashboardSubscribeRoute = mainDashboardSubscribeRouteImport.update({
  id: '/dashboard/subscribe',
  path: '/dashboard/subscribe',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainDashboardPaymentRoute = mainDashboardPaymentRouteImport.update({
  id: '/dashboard/payment',
  path: '/dashboard/payment',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAuthenticationMagicRoute = mainAuthenticationMagicRouteImport.update({
  id: '/authentication/magic',
  path: '/authentication/magic',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainDashboardOnboardingsIndexRoute =
  mainDashboardOnboardingsIndexRouteImport.update({
    id: '/dashboard/onboardings/',
    path: '/dashboard/onboardings/',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainDashboardOnboardingsProfileRoute =
  mainDashboardOnboardingsProfileRouteImport.update({
    id: '/dashboard/onboardings/profile',
    path: '/dashboard/onboardings/profile',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainDashboardOnboardingsAgentRoute =
  mainDashboardOnboardingsAgentRouteImport.update({
    id: '/dashboard/onboardings/agent',
    path: '/dashboard/onboardings/agent',
    getParentRoute: () => mainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authentication/magic': typeof mainAuthenticationMagicRoute
  '/dashboard/payment': typeof mainDashboardPaymentRoute
  '/dashboard/subscribe': typeof mainDashboardSubscribeRoute
  '/dashboard/whatsapp': typeof mainDashboardWhatsappRoute
  '/pages/about': typeof mainPagesAboutRoute
  '/pages/contact': typeof mainPagesContactRoute
  '/pages/help': typeof mainPagesHelpRoute
  '/pages/privacy-policy': typeof mainPagesPrivacyPolicyRoute
  '/pages/terms-of-service': typeof mainPagesTermsOfServiceRoute
  '/dashboard': typeof mainDashboardIndexRoute
  '/pages': typeof mainPagesIndexRoute
  '/dashboard/onboardings/agent': typeof mainDashboardOnboardingsAgentRoute
  '/dashboard/onboardings/profile': typeof mainDashboardOnboardingsProfileRoute
  '/dashboard/onboardings': typeof mainDashboardOnboardingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authentication/magic': typeof mainAuthenticationMagicRoute
  '/dashboard/payment': typeof mainDashboardPaymentRoute
  '/dashboard/subscribe': typeof mainDashboardSubscribeRoute
  '/dashboard/whatsapp': typeof mainDashboardWhatsappRoute
  '/pages/about': typeof mainPagesAboutRoute
  '/pages/contact': typeof mainPagesContactRoute
  '/pages/help': typeof mainPagesHelpRoute
  '/pages/privacy-policy': typeof mainPagesPrivacyPolicyRoute
  '/pages/terms-of-service': typeof mainPagesTermsOfServiceRoute
  '/dashboard': typeof mainDashboardIndexRoute
  '/pages': typeof mainPagesIndexRoute
  '/dashboard/onboardings/agent': typeof mainDashboardOnboardingsAgentRoute
  '/dashboard/onboardings/profile': typeof mainDashboardOnboardingsProfileRoute
  '/dashboard/onboardings': typeof mainDashboardOnboardingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(main)': typeof mainRouteRouteWithChildren
  '/(main)/authentication/magic': typeof mainAuthenticationMagicRoute
  '/(main)/dashboard/payment': typeof mainDashboardPaymentRoute
  '/(main)/dashboard/subscribe': typeof mainDashboardSubscribeRoute
  '/(main)/dashboard/whatsapp': typeof mainDashboardWhatsappRoute
  '/(main)/pages/about': typeof mainPagesAboutRoute
  '/(main)/pages/contact': typeof mainPagesContactRoute
  '/(main)/pages/help': typeof mainPagesHelpRoute
  '/(main)/pages/privacy-policy': typeof mainPagesPrivacyPolicyRoute
  '/(main)/pages/terms-of-service': typeof mainPagesTermsOfServiceRoute
  '/(main)/dashboard/': typeof mainDashboardIndexRoute
  '/(main)/pages/': typeof mainPagesIndexRoute
  '/(main)/dashboard/onboardings/agent': typeof mainDashboardOnboardingsAgentRoute
  '/(main)/dashboard/onboardings/profile': typeof mainDashboardOnboardingsProfileRoute
  '/(main)/dashboard/onboardings/': typeof mainDashboardOnboardingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authentication/magic'
    | '/dashboard/payment'
    | '/dashboard/subscribe'
    | '/dashboard/whatsapp'
    | '/pages/about'
    | '/pages/contact'
    | '/pages/help'
    | '/pages/privacy-policy'
    | '/pages/terms-of-service'
    | '/dashboard'
    | '/pages'
    | '/dashboard/onboardings/agent'
    | '/dashboard/onboardings/profile'
    | '/dashboard/onboardings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authentication/magic'
    | '/dashboard/payment'
    | '/dashboard/subscribe'
    | '/dashboard/whatsapp'
    | '/pages/about'
    | '/pages/contact'
    | '/pages/help'
    | '/pages/privacy-policy'
    | '/pages/terms-of-service'
    | '/dashboard'
    | '/pages'
    | '/dashboard/onboardings/agent'
    | '/dashboard/onboardings/profile'
    | '/dashboard/onboardings'
  id:
    | '__root__'
    | '/'
    | '/(main)'
    | '/(main)/authentication/magic'
    | '/(main)/dashboard/payment'
    | '/(main)/dashboard/subscribe'
    | '/(main)/dashboard/whatsapp'
    | '/(main)/pages/about'
    | '/(main)/pages/contact'
    | '/(main)/pages/help'
    | '/(main)/pages/privacy-policy'
    | '/(main)/pages/terms-of-service'
    | '/(main)/dashboard/'
    | '/(main)/pages/'
    | '/(main)/dashboard/onboardings/agent'
    | '/(main)/dashboard/onboardings/profile'
    | '/(main)/dashboard/onboardings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  mainRouteRoute: typeof mainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/pages/': {
      id: '/(main)/pages/'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof mainPagesIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/dashboard/': {
      id: '/(main)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof mainDashboardIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/pages/terms-of-service': {
      id: '/(main)/pages/terms-of-service'
      path: '/pages/terms-of-service'
      fullPath: '/pages/terms-of-service'
      preLoaderRoute: typeof mainPagesTermsOfServiceRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/pages/privacy-policy': {
      id: '/(main)/pages/privacy-policy'
      path: '/pages/privacy-policy'
      fullPath: '/pages/privacy-policy'
      preLoaderRoute: typeof mainPagesPrivacyPolicyRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/pages/help': {
      id: '/(main)/pages/help'
      path: '/pages/help'
      fullPath: '/pages/help'
      preLoaderRoute: typeof mainPagesHelpRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/pages/contact': {
      id: '/(main)/pages/contact'
      path: '/pages/contact'
      fullPath: '/pages/contact'
      preLoaderRoute: typeof mainPagesContactRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/pages/about': {
      id: '/(main)/pages/about'
      path: '/pages/about'
      fullPath: '/pages/about'
      preLoaderRoute: typeof mainPagesAboutRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/dashboard/whatsapp': {
      id: '/(main)/dashboard/whatsapp'
      path: '/dashboard/whatsapp'
      fullPath: '/dashboard/whatsapp'
      preLoaderRoute: typeof mainDashboardWhatsappRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/dashboard/subscribe': {
      id: '/(main)/dashboard/subscribe'
      path: '/dashboard/subscribe'
      fullPath: '/dashboard/subscribe'
      preLoaderRoute: typeof mainDashboardSubscribeRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/dashboard/payment': {
      id: '/(main)/dashboard/payment'
      path: '/dashboard/payment'
      fullPath: '/dashboard/payment'
      preLoaderRoute: typeof mainDashboardPaymentRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/authentication/magic': {
      id: '/(main)/authentication/magic'
      path: '/authentication/magic'
      fullPath: '/authentication/magic'
      preLoaderRoute: typeof mainAuthenticationMagicRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/dashboard/onboardings/': {
      id: '/(main)/dashboard/onboardings/'
      path: '/dashboard/onboardings'
      fullPath: '/dashboard/onboardings'
      preLoaderRoute: typeof mainDashboardOnboardingsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/dashboard/onboardings/profile': {
      id: '/(main)/dashboard/onboardings/profile'
      path: '/dashboard/onboardings/profile'
      fullPath: '/dashboard/onboardings/profile'
      preLoaderRoute: typeof mainDashboardOnboardingsProfileRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/dashboard/onboardings/agent': {
      id: '/(main)/dashboard/onboardings/agent'
      path: '/dashboard/onboardings/agent'
      fullPath: '/dashboard/onboardings/agent'
      preLoaderRoute: typeof mainDashboardOnboardingsAgentRouteImport
      parentRoute: typeof mainRouteRoute
    }
  }
}

interface mainRouteRouteChildren {
  mainAuthenticationMagicRoute: typeof mainAuthenticationMagicRoute
  mainDashboardPaymentRoute: typeof mainDashboardPaymentRoute
  mainDashboardSubscribeRoute: typeof mainDashboardSubscribeRoute
  mainDashboardWhatsappRoute: typeof mainDashboardWhatsappRoute
  mainPagesAboutRoute: typeof mainPagesAboutRoute
  mainPagesContactRoute: typeof mainPagesContactRoute
  mainPagesHelpRoute: typeof mainPagesHelpRoute
  mainPagesPrivacyPolicyRoute: typeof mainPagesPrivacyPolicyRoute
  mainPagesTermsOfServiceRoute: typeof mainPagesTermsOfServiceRoute
  mainDashboardIndexRoute: typeof mainDashboardIndexRoute
  mainPagesIndexRoute: typeof mainPagesIndexRoute
  mainDashboardOnboardingsAgentRoute: typeof mainDashboardOnboardingsAgentRoute
  mainDashboardOnboardingsProfileRoute: typeof mainDashboardOnboardingsProfileRoute
  mainDashboardOnboardingsIndexRoute: typeof mainDashboardOnboardingsIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainAuthenticationMagicRoute: mainAuthenticationMagicRoute,
  mainDashboardPaymentRoute: mainDashboardPaymentRoute,
  mainDashboardSubscribeRoute: mainDashboardSubscribeRoute,
  mainDashboardWhatsappRoute: mainDashboardWhatsappRoute,
  mainPagesAboutRoute: mainPagesAboutRoute,
  mainPagesContactRoute: mainPagesContactRoute,
  mainPagesHelpRoute: mainPagesHelpRoute,
  mainPagesPrivacyPolicyRoute: mainPagesPrivacyPolicyRoute,
  mainPagesTermsOfServiceRoute: mainPagesTermsOfServiceRoute,
  mainDashboardIndexRoute: mainDashboardIndexRoute,
  mainPagesIndexRoute: mainPagesIndexRoute,
  mainDashboardOnboardingsAgentRoute: mainDashboardOnboardingsAgentRoute,
  mainDashboardOnboardingsProfileRoute: mainDashboardOnboardingsProfileRoute,
  mainDashboardOnboardingsIndexRoute: mainDashboardOnboardingsIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  mainRouteRoute: mainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
